name: "Replace tabs"
on: push
jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
    - name: "Check out the repo"
      uses: actions/checkout@v2
      
    - name: "Replace tabs in text files with spaces"
      run: |
        # Make whatever changes you'd like here. Remove trailing whitespace, add copyright notices, generate docs, etc...
        # `git grep` is used here to find non-binary files.
        git grep --name-only -e . | xargs perl -pi -e 's/\t/  /g'

    - name: "Any changes made?"
      id: dirty-check
      run: |
        # Set `git-status` so we can skip the step below if the workspace is clean.
        git status
        echo ::set-output name=git-status::`git status --porcelain`
        
    - name: "Add, commit and push changes"
      if: steps.dirty-check.outputs.git-status != ''
      run: |
        git add .
        git commit -m "Richard was wrong. #TeamWinnie"
        git push
